import { Node, Edge } from './types';

export const mockNodes: Node[] = [
  // REPOSITORIES (10)
  {
    id: '1',
    type: 'repo',
    title: 'entropy-core',
    description: 'Core graph engine and AI orchestration system for the Entropy platform',
    metadata: {
      language: 'TypeScript',
      stars: 142,
      lastCommit: '2 hours ago',
      url: 'https://github.com/entropy/entropy-core',
      status: 'active',
      visibility: 'public',
    },
    position: { x: 400, y: 300 },
    connections: ['2', '3', '5', '11', '21'],
    tags: ['core', 'engine', 'ai'],
  },
  {
    id: '2',
    type: 'repo',
    title: 'entropy-web',
    description: 'Next.js frontend application with real-time graph visualization',
    metadata: {
      language: 'TypeScript',
      stars: 89,
      lastCommit: '4 hours ago',
      url: 'https://github.com/entropy/entropy-web',
      status: 'active',
      visibility: 'public',
    },
    position: { x: 600, y: 250 },
    connections: ['1', '4', '12', '13'],
    tags: ['frontend', 'react', 'visualization'],
  },
  {
    id: '3',
    type: 'repo',
    title: 'graph-physics',
    description: 'D3.js force simulation with custom physics for knowledge graphs',
    metadata: {
      language: 'TypeScript',
      stars: 234,
      lastCommit: '1 day ago',
      url: 'https://github.com/entropy/graph-physics',
      status: 'active',
      visibility: 'public',
    },
    position: { x: 300, y: 450 },
    connections: ['1', '2', '6'],
    tags: ['physics', 'd3', 'simulation'],
  },
  {
    id: '4',
    type: 'repo',
    title: 'ai-agents',
    description: 'Autonomous AI agents for task orchestration and workflow automation',
    metadata: {
      language: 'Python',
      stars: 567,
      lastCommit: '6 hours ago',
      url: 'https://github.com/entropy/ai-agents',
      status: 'active',
      visibility: 'public',
    },
    position: { x: 700, y: 400 },
    connections: ['1', '21', '22', '14'],
    tags: ['ai', 'agents', 'automation'],
  },
  {
    id: '5',
    type: 'repo',
    title: 'entropy-api',
    description: 'GraphQL API gateway for unified data access across integrations',
    metadata: {
      language: 'Go',
      stars: 78,
      lastCommit: '12 hours ago',
      url: 'https://github.com/entropy/entropy-api',
      status: 'active',
      visibility: 'private',
    },
    position: { x: 500, y: 500 },
    connections: ['1', '6', '7', '15'],
    tags: ['api', 'graphql', 'backend'],
  },
  {
    id: '6',
    type: 'repo',
    title: 'integrations-sdk',
    description: 'SDK for building custom integrations with third-party services',
    metadata: {
      language: 'TypeScript',
      stars: 45,
      lastCommit: '2 days ago',
      url: 'https://github.com/entropy/integrations-sdk',
      status: 'active',
      visibility: 'public',
    },
    position: { x: 200, y: 350 },
    connections: ['3', '5', '8'],
    tags: ['sdk', 'integrations'],
  },
  {
    id: '7',
    type: 'repo',
    title: 'entropy-cli',
    description: 'Command-line interface for Entropy workspace management',
    metadata: {
      language: 'Rust',
      stars: 156,
      lastCommit: '3 days ago',
      url: 'https://github.com/entropy/entropy-cli',
      status: 'active',
      visibility: 'public',
    },
    position: { x: 650, y: 550 },
    connections: ['5', '8'],
    tags: ['cli', 'rust', 'tooling'],
  },
  {
    id: '8',
    type: 'repo',
    title: 'vector-db',
    description: 'Custom vector database for semantic search and embeddings',
    metadata: {
      language: 'Rust',
      stars: 312,
      lastCommit: '1 week ago',
      url: 'https://github.com/entropy/vector-db',
      status: 'active',
      visibility: 'public',
    },
    position: { x: 350, y: 600 },
    connections: ['6', '7', '4'],
    tags: ['database', 'vector', 'search'],
  },
  {
    id: '9',
    type: 'repo',
    title: 'entropy-mobile',
    description: 'React Native mobile app for on-the-go workspace access',
    metadata: {
      language: 'TypeScript',
      stars: 67,
      lastCommit: '5 days ago',
      url: 'https://github.com/entropy/entropy-mobile',
      status: 'draft',
      visibility: 'private',
    },
    position: { x: 800, y: 300 },
    connections: ['2', '5'],
    tags: ['mobile', 'react-native'],
  },
  {
    id: '10',
    type: 'repo',
    title: 'design-system',
    description: 'Shared component library and design tokens for Entropy products',
    metadata: {
      language: 'TypeScript',
      stars: 98,
      lastCommit: '8 hours ago',
      url: 'https://github.com/entropy/design-system',
      status: 'active',
      visibility: 'public',
    },
    position: { x: 150, y: 200 },
    connections: ['2', '9', '13'],
    tags: ['design', 'components', 'ui'],
  },

  // DOCUMENTS (8)
  {
    id: '11',
    type: 'doc',
    title: 'Product Roadmap Q1 2025',
    description: 'Strategic initiatives and feature priorities for the upcoming quarter',
    metadata: {
      app: 'Notion',
      lastEdited: '1 hour ago',
      status: 'active',
    },
    position: { x: 450, y: 150 },
    connections: ['1', '12', '16', '17'],
    tags: ['roadmap', 'planning', 'strategy'],
  },
  {
    id: '12',
    type: 'doc',
    title: 'API Documentation v2.0',
    description: 'Complete reference guide for the Entropy GraphQL API',
    metadata: {
      app: 'Notion',
      lastEdited: '3 hours ago',
      status: 'active',
    },
    position: { x: 550, y: 100 },
    connections: ['2', '5', '11'],
    tags: ['documentation', 'api', 'reference'],
  },
  {
    id: '13',
    type: 'doc',
    title: 'Design Principles',
    description: 'Core design philosophy and interaction patterns for Entropy',
    metadata: {
      app: 'Figma',
      lastEdited: '2 days ago',
      status: 'active',
    },
    position: { x: 250, y: 100 },
    connections: ['2', '10', '14'],
    tags: ['design', 'principles', 'ux'],
  },
  {
    id: '14',
    type: 'doc',
    title: 'AI Agent Architecture',
    description: 'Technical specification for autonomous agent system design',
    metadata: {
      app: 'Google Docs',
      lastEdited: '4 hours ago',
      status: 'active',
    },
    position: { x: 800, y: 450 },
    connections: ['4', '13', '21', '22'],
    tags: ['architecture', 'ai', 'technical'],
  },
  {
    id: '15',
    type: 'doc',
    title: 'Security Audit Report',
    description: 'Third-party security assessment findings and remediation plan',
    metadata: {
      app: 'Notion',
      lastEdited: '1 week ago',
      status: 'active',
    },
    position: { x: 600, y: 650 },
    connections: ['5', '16'],
    tags: ['security', 'audit', 'compliance'],
  },
  {
    id: '16',
    type: 'doc',
    title: 'Investor Update - Nov 2024',
    description: 'Monthly progress report for stakeholders and board members',
    metadata: {
      app: 'Google Docs',
      lastEdited: '5 days ago',
      status: 'active',
    },
    position: { x: 350, y: 50 },
    connections: ['11', '15', '17'],
    tags: ['investors', 'update', 'business'],
  },
  {
    id: '17',
    type: 'doc',
    title: 'User Research Findings',
    description: 'Synthesis of user interviews and usability testing sessions',
    metadata: {
      app: 'Notion',
      lastEdited: '3 days ago',
      status: 'active',
    },
    position: { x: 500, y: 0 },
    connections: ['11', '16', '13'],
    tags: ['research', 'users', 'insights'],
  },
  {
    id: '18',
    type: 'doc',
    title: 'Onboarding Flow Spec',
    description: 'Detailed specification for new user onboarding experience',
    metadata: {
      app: 'Figma',
      lastEdited: '6 hours ago',
      status: 'draft',
    },
    position: { x: 100, y: 400 },
    connections: ['10', '13', '19'],
    tags: ['onboarding', 'ux', 'flow'],
  },

  // TASKS/ISSUES (8)
  {
    id: '19',
    type: 'task',
    title: 'Implement OAuth2 integration',
    description: 'Add support for GitHub, Google, and Notion OAuth2 authentication',
    metadata: {
      status: 'active',
      priority: 'high',
      assignee: 'Sarah Chen',
      progress: 65,
    },
    position: { x: 100, y: 550 },
    connections: ['5', '6', '18'],
    tags: ['auth', 'oauth', 'feature'],
  },
  {
    id: '20',
    type: 'task',
    title: 'Graph performance optimization',
    description: 'Improve rendering performance for graphs with >500 nodes',
    metadata: {
      status: 'active',
      priority: 'critical',
      assignee: 'Alex Kim',
      progress: 30,
    },
    position: { x: 200, y: 500 },
    connections: ['3', '2', '23'],
    tags: ['performance', 'optimization', 'graph'],
  },
  {
    id: '21',
    type: 'task',
    title: 'AI context window expansion',
    description: 'Increase context window for better cross-document understanding',
    metadata: {
      status: 'active',
      priority: 'high',
      assignee: 'Marcus Johnson',
      progress: 80,
    },
    position: { x: 850, y: 350 },
    connections: ['1', '4', '14', '22'],
    tags: ['ai', 'context', 'nlp'],
  },
  {
    id: '22',
    type: 'task',
    title: 'Agent orchestration refactor',
    description: 'Redesign agent communication protocol for better scalability',
    metadata: {
      status: 'active',
      priority: 'medium',
      assignee: 'Emily Zhang',
      progress: 45,
    },
    position: { x: 900, y: 500 },
    connections: ['4', '14', '21'],
    tags: ['agents', 'refactor', 'architecture'],
  },
  {
    id: '23',
    type: 'task',
    title: 'Fix zoom gesture handling',
    description: 'Resolve trackpad zoom issues on Firefox and Safari',
    metadata: {
      status: 'active',
      priority: 'medium',
      assignee: 'David Park',
      progress: 90,
    },
    position: { x: 150, y: 650 },
    connections: ['2', '20', '3'],
    tags: ['bug', 'gestures', 'browser'],
  },
  {
    id: '24',
    type: 'task',
    title: 'Add keyboard shortcuts',
    description: 'Implement comprehensive keyboard navigation throughout the app',
    metadata: {
      status: 'draft',
      priority: 'low',
      assignee: 'Lisa Wang',
      progress: 10,
    },
    position: { x: 750, y: 150 },
    connections: ['2', '10'],
    tags: ['accessibility', 'keyboard', 'ux'],
  },
  {
    id: '25',
    type: 'task',
    title: 'Real-time collaboration',
    description: 'Enable multiple users to view and edit the same graph simultaneously',
    metadata: {
      status: 'draft',
      priority: 'high',
      assignee: 'Team',
      progress: 5,
    },
    position: { x: 50, y: 300 },
    connections: ['1', '5', '2'],
    tags: ['collaboration', 'realtime', 'feature'],
  },
  {
    id: '26',
    type: 'task',
    title: 'Mobile gesture support',
    description: 'Implement touch gestures for graph navigation on mobile devices',
    metadata: {
      status: 'active',
      priority: 'medium',
      assignee: 'Tom Harris',
      progress: 55,
    },
    position: { x: 900, y: 250 },
    connections: ['9', '23'],
    tags: ['mobile', 'gestures', 'touch'],
  },

  // AI AGENTS (2)
  {
    id: '27',
    type: 'ai_agent',
    title: 'Research Assistant',
    description: 'Autonomously gathers and synthesizes information across connected documents',
    metadata: {
      status: 'active',
      lastEdited: 'Active now',
    },
    position: { x: 700, y: 100 },
    connections: ['4', '11', '12', '14', '17'],
    tags: ['agent', 'research', 'synthesis'],
  },
  {
    id: '28',
    type: 'ai_agent',
    title: 'Code Reviewer',
    description: 'Analyzes pull requests and suggests improvements based on codebase context',
    metadata: {
      status: 'active',
      lastEdited: 'Active now',
    },
    position: { x: 450, y: 400 },
    connections: ['1', '2', '3', '4', '5'],
    tags: ['agent', 'code-review', 'automation'],
  },

  // MISC (2)
  {
    id: '29',
    type: 'misc',
    title: 'YC Demo Day Prep',
    description: 'Notes and materials for upcoming Y Combinator demo presentation',
    metadata: {
      app: 'Browser Tab',
      lastEdited: '30 minutes ago',
    },
    position: { x: 300, y: 200 },
    connections: ['11', '16', '27'],
    tags: ['yc', 'demo', 'presentation'],
  },
  {
    id: '30',
    type: 'misc',
    title: 'Competitor Analysis',
    description: 'Market research on Linear, Notion, and Obsidian graph features',
    metadata: {
      app: 'Notion',
      lastEdited: '2 days ago',
    },
    position: { x: 50, y: 100 },
    connections: ['11', '13', '17'],
    tags: ['research', 'competitors', 'market'],
  },
];

export const mockEdges: Edge[] = [
  // entropy-core connections
  { id: 'e1', source: '1', target: '2', type: 'part_of', strength: 1 },
  { id: 'e2', source: '1', target: '3', type: 'depends_on', strength: 0.8 },
  { id: 'e3', source: '1', target: '5', type: 'depends_on', strength: 0.9 },
  { id: 'e4', source: '1', target: '11', type: 'relates_to', strength: 0.6 },
  { id: 'e5', source: '1', target: '21', type: 'relates_to', strength: 0.7 },

  // entropy-web connections
  { id: 'e6', source: '2', target: '4', type: 'depends_on', strength: 0.5 },
  { id: 'e7', source: '2', target: '12', type: 'relates_to', strength: 0.8 },
  { id: 'e8', source: '2', target: '13', type: 'relates_to', strength: 0.7 },

  // graph-physics connections
  { id: 'e9', source: '3', target: '6', type: 'depends_on', strength: 0.4 },

  // ai-agents connections
  { id: 'e10', source: '4', target: '21', type: 'part_of', strength: 0.9 },
  { id: 'e11', source: '4', target: '22', type: 'part_of', strength: 0.8 },
  { id: 'e12', source: '4', target: '14', type: 'relates_to', strength: 1 },

  // entropy-api connections
  { id: 'e13', source: '5', target: '6', type: 'depends_on', strength: 0.6 },
  { id: 'e14', source: '5', target: '7', type: 'relates_to', strength: 0.5 },
  { id: 'e15', source: '5', target: '15', type: 'relates_to', strength: 0.8 },

  // integrations-sdk connections
  { id: 'e16', source: '6', target: '8', type: 'depends_on', strength: 0.7 },

  // entropy-cli connections
  { id: 'e17', source: '7', target: '8', type: 'depends_on', strength: 0.6 },

  // design-system connections
  { id: 'e18', source: '10', target: '2', type: 'part_of', strength: 0.9 },
  { id: 'e19', source: '10', target: '9', type: 'part_of', strength: 0.8 },
  { id: 'e20', source: '10', target: '13', type: 'relates_to', strength: 1 },

  // Document connections
  { id: 'e21', source: '11', target: '12', type: 'relates_to', strength: 0.7 },
  { id: 'e22', source: '11', target: '16', type: 'part_of', strength: 0.8 },
  { id: 'e23', source: '11', target: '17', type: 'relates_to', strength: 0.9 },
  { id: 'e24', source: '13', target: '14', type: 'relates_to', strength: 0.6 },
  { id: 'e25', source: '15', target: '16', type: 'relates_to', strength: 0.5 },
  { id: 'e26', source: '16', target: '17', type: 'relates_to', strength: 0.4 },
  { id: 'e27', source: '18', target: '10', type: 'relates_to', strength: 0.7 },
  { id: 'e28', source: '18', target: '13', type: 'depends_on', strength: 0.8 },

  // Task connections
  { id: 'e29', source: '19', target: '5', type: 'part_of', strength: 0.9 },
  { id: 'e30', source: '19', target: '6', type: 'depends_on', strength: 0.7 },
  { id: 'e31', source: '19', target: '18', type: 'relates_to', strength: 0.6 },
  { id: 'e32', source: '20', target: '3', type: 'part_of', strength: 1 },
  { id: 'e33', source: '20', target: '2', type: 'relates_to', strength: 0.8 },
  { id: 'e34', source: '20', target: '23', type: 'blocks', strength: 0.9 },
  { id: 'e35', source: '21', target: '14', type: 'relates_to', strength: 0.9 },
  { id: 'e36', source: '22', target: '14', type: 'depends_on', strength: 0.8 },
  { id: 'e37', source: '22', target: '21', type: 'relates_to', strength: 0.7 },
  { id: 'e38', source: '23', target: '2', type: 'part_of', strength: 0.8 },
  { id: 'e39', source: '23', target: '3', type: 'relates_to', strength: 0.6 },
  { id: 'e40', source: '24', target: '2', type: 'part_of', strength: 0.7 },
  { id: 'e41', source: '24', target: '10', type: 'relates_to', strength: 0.5 },
  { id: 'e42', source: '25', target: '1', type: 'part_of', strength: 0.9 },
  { id: 'e43', source: '25', target: '5', type: 'depends_on', strength: 0.8 },
  { id: 'e44', source: '26', target: '9', type: 'part_of', strength: 0.9 },
  { id: 'e45', source: '26', target: '23', type: 'relates_to', strength: 0.7 },

  // AI Agent connections
  { id: 'e46', source: '27', target: '4', type: 'part_of', strength: 1 },
  { id: 'e47', source: '27', target: '11', type: 'relates_to', strength: 0.8 },
  { id: 'e48', source: '27', target: '12', type: 'relates_to', strength: 0.7 },
  { id: 'e49', source: '27', target: '14', type: 'relates_to', strength: 0.9 },
  { id: 'e50', source: '27', target: '17', type: 'relates_to', strength: 0.6 },
  { id: 'e51', source: '28', target: '1', type: 'relates_to', strength: 0.9 },
  { id: 'e52', source: '28', target: '2', type: 'relates_to', strength: 0.9 },
  { id: 'e53', source: '28', target: '3', type: 'relates_to', strength: 0.8 },
  { id: 'e54', source: '28', target: '4', type: 'part_of', strength: 1 },
  { id: 'e55', source: '28', target: '5', type: 'relates_to', strength: 0.7 },

  // Misc connections
  { id: 'e56', source: '29', target: '11', type: 'relates_to', strength: 0.9 },
  { id: 'e57', source: '29', target: '16', type: 'relates_to', strength: 0.8 },
  { id: 'e58', source: '29', target: '27', type: 'relates_to', strength: 0.5 },
  { id: 'e59', source: '30', target: '11', type: 'relates_to', strength: 0.7 },
  { id: 'e60', source: '30', target: '13', type: 'relates_to', strength: 0.6 },
  { id: 'e61', source: '30', target: '17', type: 'relates_to', strength: 0.8 },
];

export const aiSuggestions = [
  'Summarize my workspace',
  "What's blocking me?",
  'Find connections I\'m missing',
  'Generate weekly report',
  'Analyze code dependencies',
  'Review open tasks',
];

export const recentCommands = [
  { id: 'cmd1', title: 'Open AI Chat', icon: 'sparkles', shortcut: '⌘I' },
  { id: 'cmd2', title: 'Toggle View', icon: 'layout', shortcut: '⌘.' },
  { id: 'cmd3', title: 'Export Graph', icon: 'download', shortcut: '⌘E' },
];

